name: Death-Swap
main: Britt\DeathSwap\Main
description: "Death Swap By Britt"
version: 1.13.0
author: HydroGamesTeam
api:
- 3.0.0
- 3.10.0
mcpe-protocol:
- 419
- 408
website: https://github.com/HydroGames-dev
permissions:
  ds.cmd:
    description: Permission to all DeathSwap commands
    default: op
